apiVersion: v1
kind: Service
metadata:
  name: {{ template "airflow.fullname" . }}-web
  labels:
    app: {{ template "airflow.name" . }}-web
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  selector:
    app: {{ template "airflow.name" . }}-web
    release: {{ .Release.Name }}
  ports:
    - name: web
      protocol: TCP
      port: 8080
