# Duplicate this file and put your customization here

# common settings and setting for the webserver
airflow:
  # You will need to define your frenet key:
  # Generate fernet_key with:
  #    python -c "from cryptography.fernet import Fernet; FERNET_KEY = Fernet.generate_key().decode(); print(FERNET_KEY)"
  # fernet_key: ABCDABCDABCDABCDABCDABCDABCDABCDABCDABCD
  fernet_key: ""
  service:
    type: ClusterIP
  # mount path for persistant volume
  dag_path: /dags
  # set the max number of retries during container initialization
  init_retry_loop:
  # base image for webserver/scheduler/`workers
  image: popoaq/docker-airflow
  imageTag: local
  # image_pull_policy: Always or IfNotPresent
  image_pull_policy: Always
  # Set scheduler_num_runs to control how the schduler behaves:
  #   -1 will let him looping indefinitively but it will never update the DAG
  #   1 will have the scheduler quit after each refresh, but kubernetes will restart it
  scheduler_num_runs: "-1"
  # prefix to the endpoint of the webserver
  # Ex: http://mycompany.com/airflow
  # url_prefix is "/airflow"
  url_prefix: "/airflow"
  config: {}

#celery:
#  # Number of celery workers to initialize
#  num_workers: 1

ingress:
  # enable ingress
  enabled: false
  annotations:
    # Define the annotation here to configure rewriting rules related to your Load balancer
    #
    # Please note their is a small difference between the way Airflow Web server and Flower handles
    # url_prefix in HTTP requests:
    #  - airflow webserver handles it completely, just let your load balancer to give the HTTP
    #    header like the requested URL (no special configuration neeed)
    #  - Flower wants HTTP header to behave like there was no URL prefix, and but still generates
    #    the right URL in html pages.
    #
    #    Extracted from the Flower documentation:
    #    (https://github.com/mher/flower/blob/master/docs/config.rst#url_prefix)
    #
    #        To access Flower on http://example.com/flower run it with:
    #            flower --url_prefix=flower
    #
    #        Use the following nginx configuration:
    #            server {
    #              listen 80;
    #              server_name example.com;
    #
    #              location /flower/ {
    #                rewrite ^/flower/(.*)$ /$1 break;
    #                proxy_pass http://example.com:5555;
    #                proxy_set_header Host $host;
    #              }
    #            }
    web:
      # Example for Traefik:
      # traefik.frontend.rule.type: PathPrefix
      # kubernetes.io/ingress.class: traefik
    flower:
      # Example for Traefik:
      # traefik.frontend.rule.type: PathPrefixStrip
      # kubernetes.io/ingress.class: traefik
  # hostname for both endpoint
  host: ""
  path:
    # if web is '/airflow':
    #  - UI will be accessible to '/airflow/admin'
    #  - Healthcheck is at 'http://mycompany.com/airflow/health'
    #  - api is at 'http://mycompany.com/airflow/api'
    web: /airflow
    # if flower is '/airflow/flower':
    #  - api is at 'http://mycompany.com/airflow/flower'
    flower: /airflow/flower

persistence:
  enabled: false
  ## storageClass: Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  # storageClass: default
  accessMode: ReadWriteOnce
  size: 1Gi

## Configuration values for the postgresql dependency.
## ref: https://github.com/kubernetes/charts/blob/master/stable/postgresql/README.md
##
postgresql:

  ## Use the PostgreSQL chart dependency.
  ## Set to false if bringing your own PostgreSQL.
  ##
  enabled: true

  ## If bringing your own PostgreSQL, the full uri to use
  ## e.g. postgres://airflow:changeme@my-postgres.com:5432/airflow?sslmode=disable
  ##
  # uri:

  ### PostgreSQL User to create.
  ##
  postgresUser: airflow

  ## PostgreSQL Password for the new user.
  ## If not set, a random 10 characters password will be used.
  ##
  postgresPassword: airflow

  ## PostgreSQL Database to create.
  ##
  postgresDatabase: airflow

  ## Persistent Volume Storage configuration.
  ## ref: https://kubernetes.io/docs/user-guide/persistent-volumes
  ##
  persistence:
    ## Enable PostgreSQL persistence using Persistent Volume Claims.
    ##
    enabled: false

redis:
  enabled: false
  redisPassword: redis
  persistence:
    enabled: true
